<?xml version="1.0"?>
<robot>
     <macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                  izz="${m*r*r/2}" /> 
      </macro>

      <macro name="box_inertia" params="m x y z">
        <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(x*x+z*z)/12}" iyz = "0"
                  izz="${m*(x*x+z*z)/12}" /> 
      </macro>

      <macro name="sphere_inertia" params="m r">
        <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                  iyy="${2*m*r*r/5}" iyz = "0"
                  izz="${2*m*r*r/5}" /> 
      </macro>

     <macro name="wheel" params="lr tY">

       <link name="${lr}_wheel">
        <collision>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <geometry>
           <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <geometry>
           <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
          </geometry>
          <material name="black"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <mass value="${wheelMass}"/>
          <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
        </inertial>
       </link>

        <gazebo reference="${lr}_wheel">
          <material>Gazebo/Black</material>
        </gazebo>


       <joint name="${lr}_wheel_hinge" type="continuous">
          <parent link="frontChassis"/>
          <child link="${lr}_wheel"/>
          <origin xyz="${-wheelPos+frontChassisLength/2} ${tY*wheelWidth/2+tY*frontChassisWidth/2} ${wheelRadius}" rpy="0 0 0" /> 
          <axis xyz="0 1 0" rpy="0 0 0" />
          <limit effort="100" velocity="100"/>
          <joint_properties damping="0.0" friction="0.0"/>
        </joint>


      <transmission name="${lr}_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${lr}_wheel_hinge">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${lr}Motor">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>10</mechanicalReduction>
        </actuator>
      </transmission>

     </macro>


      <macro name="casterWheel" params="lr tY">

       <link name="${lr}_casterWheel">
        <collision>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <geometry>
           <cylinder length="${casterWheelWidth}" radius="${casterWheelRadius}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <geometry>
           <cylinder length="${casterWheelWidth}" radius="${casterWheelRadius}"/>
          </geometry>
          <material name="grey"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <mass value="${casterWheelMass}"/>
          <cylinder_inertia m="${casterWheelMass}" r="${casterWheelRadius}" h="${casterWheelWidth}"/>
        </inertial>
       </link>

        <gazebo reference="${lr}_casterWheel">
          <material>Gazebo/Grey</material>
        </gazebo>


       <joint name="${lr}_casterWheel_hinge" type="continuous">
          <parent link="rearChassis"/>
          <child link="${lr}_casterWheel"/>
          <origin xyz="${casterWheelPos-rearChassisLength/2} ${tY*casterWheelWidth/2+tY*rearChassisWidth/2} ${casterWheelRadius}" rpy="0 0 0" /> 
          <axis xyz="0 1 0" rpy="0 0 0" />
          <limit effort="100" velocity="100"/>
          <joint_properties damping="0.0" friction="0.0"/>
        </joint>


    </macro>

     <macro name="wheelHold" params="lr tY">

       <link name="${lr}_wheelHold">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <box size="${wheelHoldLength} ${wheelHoldWidth} ${wheelHoldHeight}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <box size="${wheelHoldLength} ${wheelHoldWidth} ${wheelHoldHeight}"/>
          </geometry>
          <material name="grey"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <mass value="${wheelHoldMass}"/>
          <box_inertia m="${wheelHoldMass}" x="${wheelHoldLength}" y="${wheelHoldWidth}" z="${wheelHoldHeight}"/>
        </inertial>
       </link>

        <gazebo reference="${lr}_wheelHold">
          <material>Gazebo/Orange</material>
        </gazebo>


       <joint name="${lr}_wheelHold_connection" type="fixed">
          <parent link="midChassis"/>
          <child link="${lr}_wheelHold"/>
          <origin xyz="${wheelHoldLength/10} ${tY*wheelHoldWidth/2+tY*midChassisWidth/2} ${wheelHoldHeight/2}" rpy="0 0 0" /> 
        </joint>


    </macro>

    <macro name="wheelCover" params="lr tY">

       <link name="${lr}_wheelCover">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <box size="${wheelCoverLength} ${wheelCoverWidth} ${wheelCoverHeight}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <box size="${wheelCoverLength} ${wheelCoverWidth} ${wheelCoverHeight}"/>
          </geometry>
          <material name="grey"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <mass value="${wheelCoverMass}"/>
          <box_inertia m="${wheelCoverMass}" x="${wheelCoverLength}" y="${wheelCoverWidth}" z="${wheelCoverHeight}"/>
        </inertial>
       </link>

        <gazebo reference="${lr}_wheelCover">
          <material>Gazebo/Orange</material>
        </gazebo>


       <joint name="${lr}_wheelCover_connection" type="fixed">
          <parent link="${lr}_wheelHold"/>
          <child link="${lr}_wheelCover"/>
          <origin xyz="${(wheelHoldLength+wheelCoverLength)/2} 0 ${wheelHoldHeight/2-wheelCoverHeight}" rpy="0 0 0" /> 
        </joint>


    </macro>

    <macro name="sonar" params="sonarNumber mountingPart x y z roll pitch yaw">
      <link name="sonar_${sonarNumber}">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.000000017" ixy="0" ixz="0" iyy="0.000000017" iyz="0" izz="0.000000017" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--<box size="0.01 0.01 0.01" /> -->
          <mesh filename="package://wheelchair_description/meshes/max_sonar_ez4.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
      </link>

      <joint name="sonarMounting_${sonarNumber}" type="fixed">
          <parent link="${mountingPart}"/>
          <child link="sonar_${sonarNumber}"/>
          <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}" /> 
      </joint>

    <gazebo reference="sonar_${sonarNumber}">
  <material>Gazebo/White</material>
  <sensor name="sonar${sonarNumber}" type="ray">
        <always_on>true</always_on>
        <update_rate>30</update_rate>
        <pose>0 0 0 ${roll} ${PI/2+pitch} ${yaw}</pose>
        <visualize>true</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>-${PI/360/2}</min_angle>
              <max_angle> ${PI/360/2}</max_angle>
            </horizontal>
            <vertical>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>-${PI/360/2}</min_angle>
              <max_angle> ${PI/360/2}</max_angle>
            </vertical>
          </scan>
          <range>
            <min>${sonar_min_range}</min>
            <max>${sonar_max_range}</max>
            <resolution>0.01</resolution>
          </range>
        </ray>
        <plugin name="gazebo_ros_kinetic_controller" filename="libhector_gazebo_ros_sonar.so">
          <gaussianNoise>0.005</gaussianNoise>
          <topicName>/mybot/sonar${sonarNumber}/scan</topicName>
          <frameId>sonar_${sonarNumber}</frameId>
        </plugin>
   <!--plugin name="hector_gazebo_ros_sonar" filename="">
    <updateRate>30.0</updateRate>
    <robotNamespace>/mybot</robotNamespace>
    <frameId>sonar1</frameId>
    <topicName>/mybot/sonar1/scan</topicName>
    <offset>0.0</offset>
    <drift>0.0</drift>
    <driftFrequency>10.0</driftFrequency>
    <gaussianNoise>0.01</gaussianNoise>
   </plugin-->
 </sensor>
</gazebo>

   </macro>

</robot>
